# Generated by Django 3.1.1 on 2020-09-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preptrestapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
