# Generated by Django 3.1.1 on 2020-09-15 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preptrestapi', '0002_auto_20200915_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('quantity', models.IntegerField()),
                ('ounces', models.DecimalField(decimal_places=2, max_digits=10)),
                ('container', models.CharField(max_length=25)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='water', to='preptrestapi.profile')),
            ],
            options={
                'verbose_name': 'water',
                'verbose_name_plural': 'waters',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('dob', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member', to='preptrestapi.profile')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('brand', models.CharField(max_length=75)),
                ('quantity', models.IntegerField()),
                ('ounces', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servings', models.IntegerField()),
                ('calories_per_serving', models.IntegerField()),
                ('container', models.CharField(max_length=25)),
                ('expiration_date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='food', to='preptrestapi.profile')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
            },
        ),
    ]
